### ISSUE TITLE
Magento 2.3 webhooks

### ISSUE THREAD

**Issue by clansbergen** [ingpsp/magento2#6]
**In Magento 2.3 the webhooks do not work. It seems to be an issue relating CsrfAwareActionInterface.** 

https://magento.stackexchange.com/questions/253414/magento-2-3-upgrade-breaks-http-post-requests-to-custom-module-endpoint
https://github.com/magento/magento2/issues/19712

Could this be implemented so the webhooks work for Magento 2.3? Would be great!
*Else we will ask someone to do some custom work on our end.. :)

**Comment by Marvin-Magmodules** [comment]
HI @clansbergen, sorry for the late reply, we did not get any update email from gtihub about this issue. Issue has been fixed in the latest version [v3.1.2 ](https://github.com/ingpsp/magento2/releases/tag/v3.1.2). We are closing this issue now but please feel free to reopen the issue if this still occurs.
